"""Render bounds for the diagnostic spawner, tied to the exported drawable.

GTA's GetModelDimensions can report collision bounds including BVH margin.
Those are unsuitable for placing the visible bottom on a surface. This file
is generated by the build and consumed by packaging; no hand-maintained job
field or change to the asset's origin is involved.
"""
from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path


def _bounds(raw: object) -> dict[str, list[float]]:
    if not isinstance(raw, dict):
        raise ValueError("Platzierungsdaten: Bounds fehlen.")
    result = {}
    for key in ("min", "max"):
        values = raw.get(key)
        if (not isinstance(values, (list, tuple)) or len(values) != 3
                or any(isinstance(v, bool) or not isinstance(v, (int, float))
                       or not math.isfinite(v) for v in values)):
            raise ValueError("Platzierungsdaten: Bounds muessen drei endliche Zahlen enthalten.")
        result[key] = [float(v) for v in values]
    if any(a > b for a, b in zip(result["min"], result["max"])):
        raise ValueError("Platzierungsdaten: Minimum liegt ueber Maximum.")
    return result


def write(drawable: Path, minimum: list[float], maximum: list[float]) -> Path:
    """Write only after successful export, alongside the native .ydr."""
    bounds = _bounds({"min": minimum, "max": maximum})
    data = {"version": 1, "drawable": drawable.name,
            "sha256": hashlib.sha256(drawable.read_bytes()).hexdigest(),
            "bounds": bounds}
    target = drawable.with_suffix(".placement.json")
    target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return target


def read(drawable: Path) -> dict[str, list[float]] | None:
    """Missing metadata identifies legacy builds; stale metadata is an error."""
    path = drawable.with_suffix(".placement.json")
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or data.get("version") != 1:
        raise ValueError(f"Unbekannte Platzierungsdaten: {path}")
    if (data.get("drawable") != drawable.name
            or data.get("sha256") != hashlib.sha256(drawable.read_bytes()).hexdigest()):
        raise ValueError(f"Platzierungsdaten passen nicht zur YDR: {path}. Neu bauen.")
    return _bounds(data.get("bounds"))
